import { Exo, Geist, Geist_Mono, Jura, Roboto } from "next/font/google";
import "./globals.css";
// import Header from "./componets/Header/Header";
import ClickSpark from "@/components/ClickSpark";
import Header from "./componets/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo = Exo({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-exo',
  display: 'swap',
})

const jura = Jura({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-jura',
  display: 'swap',
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-black max-w-screen min-h-full overflow-x-clip ">
              <ClickSpark
  sparkColor='#FFFFF'
  sparkSize={10}
  sparkRadius={15}
  sparkCount={8}
  duration={400}
>
      {
        <div className="sticky top-0 bg-transparent z-50 w-screen">
        <Header/>
        </div>
        
      }
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${exo.variable} ${jura.variable} ${roboto.variable} antialiased z-40 font-exo`}
      >

   {children}

       
      </body>
      </ClickSpark>
    </html>
  );
}
